name: l10n
on:
  # Run nightly at midnight UTC.
  schedule:
    - cron: "0 0 * * *"
  # Also allow manual invocation.
  workflow_dispatch:

jobs:
  update-translation-catalogs:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out securedrop-client
        uses: actions/checkout@v2
      - name: Set Git identity
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install --require-hashes -r requirements/dev-requirements.txt
      - name: Update translation catalogs
        run: make update-translation-catalogs
      - name: Push
        run: git push